amcl:
  ros__parameters:
    use_sim_time: false

    min_particles: 200
    max_particles: 800

    update_min_d: 0.25
    update_min_a: 0.3

    laser_model_type: likelihood_field
    laser_z_hit: 0.85
    laser_z_rand: 0.15
    laser_sigma_hit: 0.2
    laser_max_range: 3.5

    base_frame_id: base_footprint
    odom_frame_id: odom
    global_frame_id: map
    scan_topic: scan

