amcl:
  ros__parameters:
    use_sim_time: false

    min_particles: 200
    max_particles: 800

    update_min_d: 0.25
    update_min_a: 0.3

    laser_model_type: likelihood_field
    laser_z_hit: 0.85
    laser_z_rand: 0.15
    laser_sigma_hit: 0.2
    laser_max_range: 3.5

    base_frame_id: base_footprint
    odom_frame_id: odom
    global_frame_id: map
    scan_topic: scan



map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: /home/naraphon9/ros2_ws/oo.yaml



global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: map
      robot_base_frame: base_footprint
      robot_radius: 0.12
      update_frequency: 5.0
      publish_frequency: 2.0
      resolution: 0.05
      track_unknown_space: true

      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /scan
          data_type: LaserScan
          clearing: true
          marking: true
          max_obstacle_height: 2.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.35



local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: odom
      robot_base_frame: base_footprint
      robot_radius: 0.12
      update_frequency: 10.0
      publish_frequency: 5.0
      rolling_window: true

      width: 4
      height: 4
      resolution: 0.05

      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /scan
          data_type: LaserScan
          clearing: true
          marking: true
          max_obstacle_height: 2.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.25



nav2_planner:
  ros__parameters:
    use_sim_time: false
    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false



controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 10.0

    min_x_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001

    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      min_vel_x: 0.1
      max_vel_x: 1.0
      max_vel_theta: 1.0
      acc_lim_x: 1.0
      acc_lim_theta: 2.0

      critics:
        - RotateToGoal
        - GoalAlign
        - PathAlign
        - PathDist
        - GoalDist


bt_navigator:
  ros__parameters:
    use_sim_time: false
    default_bt_xml_filename: /home/naraphon9/ros2_ws/bt/navigate_w_replanning_and_recovery.xml

    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node



recoveries_server:
  ros__parameters:
    use_sim_time: false



lifecycle_manager:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names:
      - map_server
      - amcl
      - global_costmap
      - local_costmap
      - nav2_planner
      - controller_server
      - bt_navigator
      - recoveries_server

