ydlidar_node:
  ros__parameters:
    port: /dev/ttyUSB0
    frame_id: laser_frame
    ignore_array: ""
    baudrate: 128000
    lidar_type: 1
    device_type: 0
    isSingleChannel: true
    intensity: false
    sample_rate: 10
    fixed_resolution: true
    reversion: true
    inverted: true
    auto_reconnect: true
    support_motor_dtr: true
    angle_max: 179.9
    angle_min: -179.9
    range_max: 8.0
    range_min: 0.1
    frequency: 10.0           # ใช้ frequency 10 Hz
    scan_frequency: 10.0      # ให้ตรงกับ frequency
    invalid_range_is_inf: true
    debug: false
    ignore_timestamp: true
    reconnect_time: 2.0
    angle_compensate: true
    invalid_range_is_inf: true


